version: '3.4'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - DbProvider=Postgres
      - ConnectionStrings__Postgres=Server=db;Database=the_app;User Id=postgres;Password=mysecretpassword;
    ports:
      - "8080:80"
      - "8081:443"
  db:
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - PGDATA=/var/lib/postgresql/data/pgdata
