<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\App.Data\App.Data.csproj" />
      <ProjectReference Include="..\FastApi.EF\FastApi.EF.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Bcl.TimeProvider" Version="8.0.1" />
    </ItemGroup>

</Project>
